feat: Создание основного сервиса приложения
Vlad-Sharapov/java-explore-with-me pull request #5
Opened 2023-07-26 19:05 UTC by Vlad-Sharapov

2023-07-27 15:48 UTC, Fleaman777 requested changes

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/model/Event.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Здесь похожий вопрос, только про Lazy,
Почему не дефолтный Eager

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/admin/impl/EventAdminServiceImpl.java
> +                        "no earlier than an hour from the date of publication");
А зачем здесь конкатенация строк, почему бы не одной строкой ?

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/privates/impl/EventPrivateServiceImpl.java
> +            throw new BadRequestException("eeee");
Не очень информативный еррор месседж )

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/privates/impl/EventPrivateServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException(String.format("User with id=%s was not found", userId)));
Как насчёт того, что бы вынесли получение юзера в отдельный приватный метод, что не дублировать эту часть когда в разных методах

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/privates/impl/EventPrivateServiceImpl.java
> +        Event event = eventRepository
Аналогично с ивентом

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/privates/impl/EventPrivateServiceImpl.java
> +//                        .collect(Collectors.toList());
Закомментированный код можно удалить, что бы не занимал место и не ухудшал восприятие

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/stateclient/ClientHandler.java
> +    private static final String APP = "ewm-main-service";
Хорошо, что название сервиса вынес в отдельную константу, так значением будет проще управлять,

можно пойти дальше и добавить это значение в application.properties, если его там нет,
А если есть, то просто использовать

2023-07-27 15:48 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.CONFLICT)
Где-то в сервисах видел, что ты отдельно ловишь DataIntegrityViolation… исключение и пробрасываешь BadRequest,
Все правильно? так и задумывалось? Что на одно и тоже исключение в коде может быть 2 разных респонса. 
Или все таки в том случае тоже может быть использован этом хэндлер ?

2023-07-28 10:08 UTC, Vlad-Sharapov commented on main-service/src/main/java/ru/yandex/practicum/mainservice/compilation/model/Compilation.java
> +    @ManyToMany(fetch = FetchType.EAGER)
Тут выборка данный такая, потому что без нее при попытке ленивой выгрузки эвентов, будет выбрасыватся LazyInitializationException. Так как во всех методах подборок возвращаются данные эвентов, решил поменять выборку.

2023-07-28 10:08 UTC, Vlad-Sharapov commented on main-service/src/main/java/ru/yandex/practicum/mainservice/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.CONFLICT)
Да. Валидация по обязательным полям производится через бд. В тестах встречаются респонсы 400 и 409 для DataIntegrityViolation...

2023-07-28 20:30 UTC, Fleaman777 approved these changes

2023-07-28 20:30 UTC, Fleaman777 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/model/Event.java
> +    @ManyToOne(fetch = FetchType.LAZY)
да в принципе здесь можно было бы оставить Eager, т.к. внутри юзера нет каких-то вложенных энтити, которые могли бы устроить  n+1 проблему, 
у все поля у юзера примитивы, которые сразу бы заполнились без доп запросов в бд

2023-07-29 05:50 UTC, merged